name: Deploy to Production

on:
  push:
    branches:
      - main

env:
  DEPLOY_ENV: PRODUCTION

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - run: env
        env:
          PRODUCTION_DOMAIN: ${{ vars.PRODUCTION_DOMAIN }}