name: display_env_vars

on:
  workflow_dispatch: 

jobs:
  display-variables:
    name: ${{ vars.JOB_NAME }}
    # You can use configuration variables with the `vars` context for dynamic jobs
    runs-on:  ubuntu-latest
    environment: PRODUCTION
    steps:
    - name: Use variables
      run: |
        echo "repository variable : $REPOSITORY_VAR"
        echo "organization variable : $ORGANIZATION_VAR"
        echo "overridden variable : $OVERRIDE_VAR"
        echo "variable from shell environment : $env_var"
        echo "PRODUCTION_DOMAIN variable : $PRODUCTION_DOMAIN"
        echo "direct access PRODUCTION_DOMAIN variable : ${{ vars.PRODUCTION_DOMAIN }}"
      env:
        REPOSITORY_VAR: ${{ vars.REPOSITORY_VAR }}
        ORGANIZATION_VAR: ${{ vars.ORGANIZATION_VAR }}
        OVERRIDE_VAR: ${{ vars.OVERRIDE_VAR }}
        PRODUCTION_DOMAIN: ${{ vars.PRODUCTION_DOMAIN }}
        
    - name: ${{ vars.HELLO_WORLD_STEP }}
      if: ${{ vars.HELLO_WORLD_ENABLED == 'true' }}
      uses: actions/hello-world-javascript-action@main
      with:
        who-to-greet: ${{ vars.GREET_NAME }}
